sudo: required

git:
    depth: 1

language: php

php:
    - '5.6'
    - '7.0'

services:
    - docker

cache:
    directories:
        - $HOME/.composer/cache

install:
    - cd $HOME
    - git clone git://github.com/alanxz/rabbitmq-c.git
    - cd $HOME/rabbitmq-c
    - git submodule init && git submodule update
    - autoreconf -i && ./configure --prefix=$HOME/rabbitmq-c && make && make install
    - cd $HOME
    - git clone git://github.com/pdezwart/php-amqp.git
    - cd $HOME/php-amqp
    - phpize && ./configure  --with-librabbitmq-dir=$HOME/rabbitmq-c && make
    - composer self-update
    - composer update --prefer-source

script:
    - bin/phpunit --exclude-group=functional
#    - bin/sandbox -bt
