sudo: required

git:
    depth: 1

language: php

php:
    - '5.6'
    - '7.0'

services:
    - docker

cache:
    directories:
        - $HOME/.composer/cache

install:
    - sudo apt-get update && sudo apt-get install -y --no-install-recommends librabbitmq
    - pecl install amqp
    - composer self-update
    - composer update --prefer-source

script:
    - bin/phpunit --exclude-group=functional
#    - bin/sandbox -bt
