sudo: required

git:
    depth: 1

language: php

php:
    - '5.6'
    - '7.0'

services:
    - docker

cache:
    directories:
        - $HOME/.composer/cache

install:
    - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - composer update --prefer-source

script:
    - bin/sandbox -bt
