sudo: required

git:
    depth: 1

language: php

php:
    - '5.6'
    - '7.0'

services:
    - docker

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer self-update
    - composer update --prefer-source --ignore-platform-reqs

script:
    - bin/phpunit
#    - bin/sandbox -bt
