sudo: false

git:
    depth: 1

language: php

php:
    - '5.6'
    - '7.0'

services:
    - mysql

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer self-update
    - composer install --prefer-source

script:
    - vendor/bin/phpunit
