sudo: required

git:
    depth: 1

language: php

php:
    - '5.6'
    - '7.0'

services:
    - docker

cache:
    directories:
        - $HOME/.composer/cache

install:
    - ls ~/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/no-debug-zts-20131226/
    - ls ~/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/no-debug-zts-20151012/
    - composer self-update
    - composer update --prefer-source

script:
    - bin/phpunit --exclude-group=functional
#    - bin/sandbox -bt
