sudo: required

git:
    depth: 1

language: php

php:
    - '5.6'
    - '7.0'

services:
    - docker

cache:
    directories:
        - $HOME/.composer/cache

install:
    - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -cs) main universe multiverse restricted"
    - sudo apt-get update && sudo apt-get install -y --no-install-recommends librabbitmq4
    - pecl install amqp
    - composer self-update
    - composer update --prefer-source

script:
    - bin/phpunit --exclude-group=functional
#    - bin/sandbox -bt
