version: '2'
services:
  sandbox:
    build: { context: ., dockerfile: Dockerfile.sandbox }
    depends_on:
      - rabbitmq
    volumes:
      - ./:/mqs
    environment:
      - FORMAPRO_MESSAGE_QUEUE_FUNCTIONAL_TESTS=1
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=mqs
      - RABBITMQ_AMQP_PORT=5672
      - RABBITMQ_STOMP_PORT=61613
  rabbitmq:
    build: { context: ., dockerfile: Dockerfile.rabbitmq }
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=mqs
