#!/usr/bin/env php
<?php

$env = 'test';
$debug = false;

foreach ([__DIR__.'/../../../vendor/autoload.php', __DIR__.'/../../../../../vendor/autoload.php'] as $autoload) {
    if (file_exists($autoload)) {
        require_once $autoload;

        break;
    }
}

require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->run($input);
