services:
    fp_message_queue.consumption.doctrine_clear_identity_map_extension:
        class: 'FormaPro\MessageQueueBundle\Consumption\Extension\DoctrineClearIdentityMapExtension'
        public: false
        arguments:
            - '@doctrine'
        tags:
            - { name: 'fp_message_queue.consumption.extension' }
