sudo: false

git:
    depth: 1

language: php

php:
    - '5.6'
    - '7.0'

env:
    - SYMFONY__DB__DRIVER=pdo_mysql SYMFONY__DB__HOST=localhost SYMFONY__DB__PORT="" SYMFONY__DB__NAME=message_queue SYMFONY__DB__USER=root SYMFONY__DB__PASSWORD=""

services:
    - mysql

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer self-update
    - composer install --prefer-source
    - Tests/Functional/app/console doctrine:database:create
    - Tests/Functional/app/console doctrine:schema:update --force

script:
    - vendor/bin/phpunit
